export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  ADMIN_SYSTEME = 'ROLE_ADMIN_SYSTEME',
  ADMIN_COMMERCIAL = 'ROLE_ADMIN_COMMERCIAL',
  COMMERCIAL = 'ROLE_COMMERCIAL',
  MAGASINIER = 'ROLE_MAGASINIER',
  CHEF_PARC = 'ROLE_CHEF_PARC',
  RESPONSABLE_PV = 'ROLE_RESPONSABLE_PV',
  VENDEUR = 'ROLE_VENDEUR',
  ADMIN_CLIENT = 'ROLE_ADMIN_CLIENT',
}
