export enum DocumentType {
  DELIVERY_NOTE = 'DELIVERY_NOTE',

  INVOICE = 'INVOICE',

  CONTRACT = 'CONTRACT',

  AMENDMENT = 'AMENDMENT',

  AUDIT_REPORT = 'AUDIT_REPORT',

  PURCHASE_ORDER = 'PURCHASE_ORDER',

  OTHER = 'OTHER',
}
