export enum ClientType {
  NATIONAL_DISTRIBUTOR = 'NATIONAL_DISTRIBUTOR',

  REGIONAL_WHOLESALER = 'REGIONAL_WHOLESALER',

  INDEPENDENT_POS = 'INDEPENDENT_POS',

  TELECOM_OPERATOR = 'TELECOM_OPERATOR',
}
